# .github/workflows/android-build.yml
name: Build Flutter Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-release-apk:
    runs-on: ubuntu-latest

    steps:
      # 1) چک‌اوت سورس شما
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) تنظیم Git برای درج توکن در همه‌ی URL‌های https://github.com/
      #    تا pub get بتواند مخازن خصوصی را clone کند
      - name: Configure Git for private deps
        run: |
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/" 
        # این خط باعث می‌شود هر clone از github.com با توکن اجرا شود 0

      # 3) نصب Flutter (آخرین نسخهٔ stable)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 4) دریافت تمام وابستگی‌ها (شامل مخازن خصوصی)
      - name: Get dependencies
        run: flutter pub get

      # 5) ساخت APK نسخهٔ release
      - name: Build APK (release)
        run: flutter build apk --release

      # 6) آپلود APK به عنوان Artifact برای دانلود
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
