# .github/workflows/android-build.yml
name: Build Karing Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    env:
      # این Secret را در Settings → Secrets تعریف کن
      VPN_PAT: ${{ secrets.VPN_PAT }}

    steps:
      # 1) چک‌اوت سورس اصلی
      - name: Checkout Karing
        uses: actions/checkout@v4

      # 2) کلون پلاگین خصوصی vpn-service در مسیر ../vpn-service
      - name: Clone private vpn-service plugin
        run: |
          git clone https://$VPN_PAT@github.com/KaringX/vpn-service.git ../vpn-service

      # 3) نصب Flutter (آخرین نسخه‌ی پایدار)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 4) دریافت وابستگی‌ها (حالا vpn-service موجود است)
      - name: Get dependencies
        run: flutter pub get

      # 5) بیلد APK نسخه‌ی Release (یک APK «fat»)
      - name: Build APK (release)
        run: flutter build apk --release

      # 6) آپلود APK به عنوان Artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: karing-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
